### ISSUE TITLE
Query.Where issue with KeyValuePair collections

### ISSUE THREAD

**Issue by DmxDev** [dolifer/NGql#9]
Steps to reproduce : 
- Try to use `Query.Where(string key, object where)` method to add query conditions; pass `IDicitionary<string, string>` as `where` arg;
- Expected result : `table_name(condition:{ k1:"v1", k2:"v2"})`;
- Actual result : `table_name(condition:{{Key:"operator", Value:"3"}, {Key:"brand", Value:"2"}})`;
- Possible root cause : QueryTextBuilder expects exact `KeyValuePair<string, object>`  (not `KeyValuePair<string, string>`).

**Comment by dolifer** [comment]
@DmxDev please check with pre-release package `1.1.1-alpha.0.1`
